### ISSUE TITLE
[FEATURE] Add Metadata template requirement for Stored Procedures/Functions

### ISSUE THREAD

**Issue by rbollineni-align** [GoogleCloudPlatform/datacatalog-connectors-rdbms#63]
**What would you like to be added**: 
This is for the sqlserver connector specifically, after testing out the new stored procedure/function feature. 
A standardized template for metadata which can then be filled out per stored procedure/function and added as a comment in the object SQL. For example, a stored procedure template would ask for its name, purpose, inputs and outputs, etc:

```sql
/*
<gdc>
<spnam>sp_calculateOrder</spname>
<sppurpose>This stored procedure will calculate orders.</sppurpose>
<spin>string:in1</spin>
<spout>int:out1</spout>
</gdc>
*/ 

/* Rest of stored procedure code follows... */
```

A structured comment can be easily parsed and attached to a stored procedure or function entry as a tag. The comment information can replace the Definition field while maintaining the other ones(DB/Schema name, access type).

**Why is this needed**:
Currently the data catalog displays the entire stored procedure in the Definition tag. However, this may be superfluous or confusing for our business users. Instead, the template provides an internally defined purpose for the object along with other valuable metadata. This would then be pulled into the data catalog and provide a simple tag with more information for our business users.

**Comment by mesmacosta** [comment]
@rbollineni-align thanks for opening this.

This seems like a good approach to enrich the metadata we are currently scrapping for the sql objects component (stored_procedure/function/etc).

The connector works with **yaml** config files, what if we used the **yaml** syntax in this standardized template comment?

Also make it more generic so same structure would be used by stored_procedures/functions/etc:
```
/*
[START_METADATA_DEFINITION]
metadata_definition:
  - name: 'sp_calculateOrder'
     purpose: 'This stored procedure will calculate orders.'
     inputs:
       - name: 'in1'
          type: 'string'
     outputs:
       - name: 'out1'
          type: 'int'
[END_METADATA_DEFINITION]

Other comments...
*/

/* Rest of stored procedure code follows... */
```

It could be optional, if there is a metadata definition available, it will be used, otherwise it uses the stored procedure code.

WDYT? Would this work for your usecase?

**Comment by rbollineni-align** [comment]
Hi @mesmacosta,

Thanks. This template in yaml syntax will work for our use case.

**Comment by mesmacosta** [comment]
@ricardolsmendes what are your thoughts? Maybe we could create something that could be used outside of the **rdbms** connectors. Like if the BI connectors have access to the comments on the sql statements.

**Comment by ricardolsmendes** [comment]
Hi, @rbollineni-align and @mesmacosta,
Thanks for bringing up such a new feature for the Data Catalog Connectors!

Marcelo, I agree with you: we should try to add something more generic, so other connectors could leverage it. The main benefit of this approach is that it could be used to ingest metadata from any asset which content comes as a parseable text. However, I don't see immediate adoption for the BI connectors -- I'm going to explain this by the end of the comment.

Regarding the Tags:
1. We need to find a generic yet meaningful Tag Template name that clearly describes its intended usage. I thought about **User-provided definition** (id: `user_provided_definition`). Does it make sense for you, folks?
2. I believe the metadata definition delimiters should let it clear it is used in Google Data Catalog. It might help people who are not aware of this integration to get a bit o context and look for further details when they read such a comment:
```
/*
[GOOGLE_DATA_CATALOG_METADATA_DEFINITION_START]
metadata_definition:
  - name: 'sp_calculateOrder'
    purpose: 'This stored procedure will calculate orders.'
    inputs:
      - name: 'in1'
        type: 'string'
    outputs:
      - name: 'out1'
        type: 'int'
[GOOGLE_DATA_CATALOG_METADATA_DEFINITION_END]

Other comments...
*/

/* Rest of stored procedure code follows... */
```
3. How to handle the input and output lists? I understand they might have variable sizes. Should we "serialize" them as comma-separated strings as we already do when ingesting other value lists?

Finally, clarifying why I don't see immediate usage for the BI connectors... The only BI connector that currently ingests SQL-related metadata is the Looker connector. SQL statements come from the [Looker query objects](https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/query#get_query), which can be created automatically in Looker as users explore data or explicitly using the API. Currently, we don't have any clue on the average of automatically vs manually created queries a given Looker instance holds, and the user-provided metadata would not be present in the automatically created ones. Having that said, we would need time and resources to try to get such insights before changing the connector. Anyway, if we understand it makes sense at some point, the generic approach will be ready.

Makes sense? 🤔

Best,

**Comment by rbollineni-align** [comment]
Hi @ricardolsmendes,

Thanks for the response. 

Going through your initial point: The "User-provided definition" is great. In the case that there is a single tag template which covers both functions and stored procedures, the definition can include another field which signifies the object type as 'function', 'stored_procedure', etc. Also, as is currently done, please include 'Sqlserver' at the beginning of the tag template name. 

For the second point, I am in agreement.

**Comment by mesmacosta** [comment]
Thanks @ricardolsmendes for the input, the points make sense.

And about:
`3. How to handle the input and output lists?`
Yaml syntax supports lists, it would be something like:
```
[GOOGLE_DATA_CATALOG_METADATA_DEFINITION_START]
metadata_definition:
  - name: 'sp_calculateOrder'
    purpose: 'This stored procedure will calculate orders.'
    inputs:
      - name: 'in1'
        type: 'string'
      - name: 'in2'
        type: 'string'
    outputs:
      - name: 'out1'
        type: 'int'
      - name: 'out2'
        type: 'int'
[GOOGLE_DATA_CATALOG_METADATA_DEFINITION_END]
```

I'd suggest using yaml sintax instead of comma-separated strings, WDYT?

**Comment by ricardolsmendes** [comment]
Hi @rbollineni-align,

> In the case that there is a single tag template which covers both functions and stored procedures, the definition can include another field which signifies the object type as 'function', 'stored_procedure', etc.

The asset type is already covered by the `user_specified_type` of the catalog Entry. 

> Also, as is currently done, please include 'Sqlserver' at the beginning of the tag template name.

This is covered by the `user_specified_system` field of the catalog Entry.

Should we duplicate such fields in the Tag? Could you please clarify why it would be useful?

**Comment by ricardolsmendes** [comment]
> I'd suggest using yaml sintax instead of comma-separated strings, WDYT?

Sorry, @mesmacosta, I was not clear... I've edited my question: "How to handle the input and output lists when storing them into Tag fields? I understand they might have variable sizes in the original metadata definition."

I mean, how should we represent
```
    inputs:
      - name: 'in1'
        type: 'string'
      - name: 'in2'
        type: 'string'
```
as Tag fields? I thought about a STRING field named `inputs` with `in1 (string), in2 (string)` as its value.

Makes sense?

**Comment by mesmacosta** [comment]
@ricardolsmendes I see, yea I agree we should use your suggestion of `in1 (string), in2 (string)` on the tag fields at least for the first version. The name followed by the type sounds like a good option.

> Also, as is currently done, please include 'Sqlserver' at the beginning of the tag template name.
> This is covered by the user_specified_system field of the catalog Entry.

I like adding the connector type at the beginning of the tag template name. We do that for the RDBMS connectors, this metadata definition template could do something similar.

Some pros:
- Easier to search for tagged assets on that source system.
- Access controls, you are able to separate users that are able to create or edit tags per source system. Otherwise you would need to split the templates in different projects.

Some cons:
- More templates to be managed.

Since this template could be used in many connectors, I like including the connector type in the beginning of the template. Also another benefit would be if in the future we change the template fields... Then users could roll out the changes one connector at a time.

**Comment by ricardolsmendes** [comment]
Got it, @mesmacosta. I'm ok with either approach. Thanks!

**Comment by mesmacosta** [comment]
The feature has been merged and published to PyPI, I will add a subsequent PR with instructions on how to proper use it.

@rbollineni-align it would be really helpful if you could test it out,  just add the config to any procedure/function:
```
[GOOGLE_DATA_CATALOG_METADATA_DEFINITION_START]
metadata_definition:
  - name: 'sp_calculateOrder'
    purpose: 'This stored procedure will calculate orders.'
    inputs:
      - name: 'in1'
        type: 'string'
      - name: 'in2'
        type: 'string'
    outputs:
      - name: 'out1'
        type: 'int'
      - name: 'out2'
        type: 'int'
[GOOGLE_DATA_CATALOG_METADATA_DEFINITION_END]
```
And then run the newest version of the sql_server connector.

**Comment by rbollineni-align** [comment]
Hi @mesmacosta,

I was able to set up the template in one of our stored procedures and run the updated python package. However, while the connector was running, it was unable to parse the metadata definition. Here is the full traceback:

```
WARNING:root:Error when parsing sql object definition
Traceback (most recent call last):
  File "c:\users\rbollineni\venv_dir\lib\site-packages\schema.py", line 396, in validate
    nvalue = Schema(svalue, error=e, ignore_extra_keys=i).validate(value)
  File "c:\users\rbollineni\venv_dir\lib\site-packages\schema.py", line 360, in validate
    data = Schema(dict, error=e).validate(data)
  File "c:\users\rbollineni\venv_dir\lib\site-packages\schema.py", line 431, in validate
    raise SchemaUnexpectedTypeError(message, e.format(data) if e else None)
schema.SchemaUnexpectedTypeError: [{'name': 'SMLoad_FactRevenueByCustomer', 'purpose': 'This stored procedure will calcu
late fact revenue by customer. This template is intended to demonstrate the capabilities of the sqlserver connector SP t
emplate, and does not contain accurate metadata information about SMLoad_FactRevenueByCustomer.', 'inputs': [{'name': 'i
n1', 'type': 'string'}, {'name': 'in2', 'type': 'string'}], 'outputs': [{'name': 'out1', 'type': 'int'}, {'name': 'out2'
, 'type': 'int'}]}] should be instance of 'dict'
```

Looks to be an issue with a list wrapping over the dict object. 

Thanks,
Rohith

**Comment by mesmacosta** [comment]
Hi @rbollineni-align,
Thanks for testing it out, the comment needs to follow the given structure, let me show you a working example:

```
CREATE PROCEDURE [dbo].[uspGetWhereUsedProductID_4]
    @StartProductID [int],
    @CheckDate [datetime]
AS
BEGIN
    SET NOCOUNT ON;

    /*
    [GOOGLE_DATA_CATALOG_METADATA_DEFINITION_START]
        metadata_definition:
          name: 'sp_calculateOrder'
          purpose: 'This stored procedure will calculate orders.'
          inputs:
            - name: 'in1'
              type: 'string'
            - name: 'in2'
              type: 'string'
            - name: 'in3'
              type: 'double'
          outputs:
            - name: 'out1'
              type: 'int'
            - name: 'out2'
              type: 'int'
            - name: 'out3'
              type: 'string'
    [GOOGLE_DATA_CATALOG_METADATA_DEFINITION_END]
    */

    --Use recursive query to generate a multi-level Bill of Material (i.e. all level 1 components of a level 0 assembly, all level 2 components of a level 1 assembly)
    WITH [BOM_cte]([ProductAssemblyID], [ComponentID], [ComponentDesc], [PerAssemblyQty], [StandardCost], [ListPrice], [BOMLevel], [RecursionLevel]) -- CTE name and columns
    AS (
        SELECT b.[ProductAssemblyID], b.[ComponentID], p.[Name], b.[PerAssemblyQty], p.[StandardCost], p.[ListPrice], b.[BOMLevel], 0 -- Get the initial list of components for the bike assembly
        FROM [Production].[BillOfMaterials] b
            INNER JOIN [Production].[Product] p 
            ON b.[ProductAssemblyID] = p.[ProductID] 
        WHERE b.[ComponentID] = @StartProductID 
            AND @CheckDate >= b.[StartDate] 
            AND @CheckDate <= ISNULL(b.[EndDate], @CheckDate)
        UNION ALL
        SELECT b.[ProductAssemblyID], b.[ComponentID], p.[Name], b.[PerAssemblyQty], p.[StandardCost], p.[ListPrice], b.[BOMLevel], [RecursionLevel] + 1 -- Join recursive member to anchor
        FROM [BOM_cte] cte
            INNER JOIN [Production].[BillOfMaterials] b 
            ON cte.[ProductAssemblyID] = b.[ComponentID]
            INNER JOIN [Production].[Product] p 
            ON b.[ProductAssemblyID] = p.[ProductID] 
        WHERE @CheckDate >= b.[StartDate] 
            AND @CheckDate <= ISNULL(b.[EndDate], @CheckDate)
        )
    -- Outer select from the CTE
    SELECT b.[ProductAssemblyID], b.[ComponentID], b.[ComponentDesc], SUM(b.[PerAssemblyQty]) AS [TotalQuantity] , b.[StandardCost], b.[ListPrice], b.[BOMLevel], b.[RecursionLevel]
    FROM [BOM_cte] b
    GROUP BY b.[ComponentID], b.[ComponentDesc], b.[ProductAssemblyID], b.[BOMLevel], b.[RecursionLevel], b.[StandardCost], b.[ListPrice]
    ORDER BY b.[BOMLevel], b.[ProductAssemblyID], b.[ComponentID]
    OPTION (MAXRECURSION 25) 
END;
```

Can you verify if your yaml config, uses that format?

Also could you provide an example of the stored procedure with the metadata definition comment? (masking sensitive information)

**Comment by mesmacosta** [comment]
I think our previous comments misguided you.

This is one is wrong:
```
[GOOGLE_DATA_CATALOG_METADATA_DEFINITION_START]
metadata_definition:
    name: 'sp_calculateOrder'
    purpose: 'This stored procedure will calculate orders.'
    inputs:
      - name: 'in1'
        type: 'string'
      - name: 'in2'
        type: 'string'
    outputs:
      - name: 'out1'
        type: 'int'
      - name: 'out2'
        type: 'int'
[GOOGLE_DATA_CATALOG_METADATA_DEFINITION_END]
```

This is one is right:
```
[GOOGLE_DATA_CATALOG_METADATA_DEFINITION_START]
metadata_definition:
  - name: 'sp_calculateOrder'
    purpose: 'This stored procedure will calculate orders.'
    inputs:
      - name: 'in1'
        type: 'string'
      - name: 'in2'
        type: 'string'
    outputs:
      - name: 'out1'
        type: 'int'
      - name: 'out2'
        type: 'int'
[GOOGLE_DATA_CATALOG_METADATA_DEFINITION_END]
```
The **metadata_definition** should not be a list type.
